### ISSUE TITLE
Reverse accumulator

### ISSUE THREAD

**Issue by Masynchin** [purescript/purescript-lists#214]
I was looking at List functions implementations, and came across this:

https://github.com/purescript/purescript-lists/blob/26e03e387c027ba10a65524e1b7b9c958dee1c2f/src/Data/List.purs#L414-L421

At first, this implementation suspiciously looks like it 1) makes redundant reverse and 2) couldn't handle infinite lists. Am I right? I haven't tested it.

The sources are old, so this may be a backward compatibility? If my observations above are right, I propose this version:

~~~purescript
mapMaybe :: forall a b. (a -> Maybe b) -> List a -> List b
mapMaybe f Nil = Nil
mapMaybe f (x:xs) =
  case f x of 
    Nothing -> mapMaybe f xs
    Just y -> y : mapMaybe f xs
~~~

I have the same question about usage of `reverse` in `zipWith`, `filter`, `take`, `takeWhile`, and `nubBy`.

**Comment by JordanMartinez** [comment]
Because your proposed version stack overflows: https://try.purescript.org/?code=LYewJgrgNgpgBAWQIYEsB2cDuALGAnGAKEJWAAcQ8AXOABQKgjCJPMpoBEkqkA6AGRQBnGkiFx%2BrCtThcevZAE8ARvAAUS1Wt68AlLqntZ3PgFU0AMxBQwSZbACMcMXFMPipaTQCiFizABjGjVffyCDTyNQwKpeAGEoMSF4kDQha3UoEABzCLYZABU8RVoIAgBlALwUMlFxIpKymErq2uJgVAwALi64aKDXNBQqQg70OABeOAbSiqqa2II0ZjxJgB416eLZ5vna3kxh7DjU9Ng4MBBCODgs7LgAInKeAIBrOBAAN3wLLMwhLoPa63HJwAAkcCE2BAmHBcA6ZE08FeMBgZAAkhZvN8MGo3Lw8Eg0Nl4AAGOAOUmkgD6VPJPQkAmENHRaCoBmIKLRmOxMG6vVZNAAtAA%2BRBIFTwQWELkYrE4uAAD2BAB8lXAAAagMAauAAJkmU3JUwAUhARErVR8qLg8IchPApgA5EA29DZdpIRES1RwBlWQlQKDOODKXhwNRIOCi8WS0O6aNi-hMi1RmPJwQW5SjL1IuAWRlOlDBqbJotQHPeuMFtSKxm9RVCBMTYEBMTwAt1kAF4E3F1u4mJ%2BG5n0dpVCXtwM0WxRD2fJ3oIvOdidAA

```purs
module Main where

import Prelude

import Data.List as L
import Data.Maybe (Maybe(..))
import Data.Unfoldable1 as U1

import Effect (Effect)
import Effect.Class.Console (log)
import TryPureScript as TryPureScript

main :: Effect Unit
main = TryPureScript.render =<< TryPureScript.withConsole do
  log "Stack overflows:"
  log $ show $ mapMaybe keepIfEven (U1.range 0 100_000 :: L.List Int)

keepIfEven :: Int -> Maybe Int
keepIfEven x
  | x `mod` 2 == 0 = Just x
  | otherwise = Nothing

mapMaybe :: forall a b. (a -> Maybe b) -> L.List a -> L.List b
mapMaybe f L.Nil = L.Nil
mapMaybe f (x L.: xs) =
  case f x of 
    Nothing -> mapMaybe f xs
    Just y -> y L.: mapMaybe f xs
```

**Comment by JordanMartinez** [comment]
Well, the error is "Internal Error: too much recursion" but same difference.

**Comment by natefaubion** [comment]
Data.List is a strict data type, so they can’t be infinite. Data.List.Lazy is what you would want for that.

**Comment by garyb** [comment]
The reason the proposed version stack overflows whereas the current version does not, is the current one is tail recursive, which the compiler turns into a loop.

**Comment by Masynchin** [comment]
> ...the current one is tail recursive, which the compiler turns into a loop.

It doesn't seems obvious for me, so thanks for explanation.
