### ISSUE TITLE
Name 'tail' was shadowed.

### ISSUE THREAD

**Issue by user471** [purescript/purescript-lists#33]
What does it mean? And what can I do with these errors?  

Error in module Data.List:
  Name 'tail' was shadowed.
  See https://github.com/purescript/purescript/wiki/Error-Code-ShadowedName for
more information, or to contribute content related to this error.

  Error in module Data.List:
  Name 'tail' was shadowed.
  See https://github.com/purescript/purescript/wiki/Error-Code-ShadowedName for
more information, or to contribute content related to this error.

  Error in module Data.List.Lazy:
  Name 'step' was shadowed.
  See https://github.com/purescript/purescript/wiki/Error-Code-ShadowedName for
more information, or to contribute content related to this error.

  Error in module Data.List.Lazy:
  Name 'tail' was shadowed.
  See https://github.com/purescript/purescript/wiki/Error-Code-ShadowedName for
more information, or to contribute content related to this error.

**Comment by garyb** [comment]
They're warnings rather than errors actually, I guess we need to tweak the error message to make that clear. The missing line numbers is a known bug: purescript/purescript#1165.

You can just ignore them, or if you want to make a PR, the fix is to ensure that when a value is in scope a new value with the same name is not declared.

**Comment by user471** [comment]
How could I find out 

Error in module Data.List:
Name 'tail' was shadowed.

where is the other "tail" locate?

**Comment by garyb** [comment]
Fixed as of 8c3c33ba493db450c92a03a9367285c144c9c7e0
