### ISSUE TITLE
Data.List.Lazy.Infinite

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript-lists#64]
It would be useful to have a type that only inhabits infinite lists:

```
data List a = Cons a (Lazy (List a))
```

Some methods in `Data.List.Lazy` would then return `Infinite` instead:

```
cycle :: forall a. List a -> Infinite.List a
```

And functions like `head` and `tail` would be non-`Maybe` total, and `init` and `last` absent, providing extra safety. No `Eq` and `Ord` either.

**Comment by Thimoteus** [comment]
Ahh, I published [this](https://pursuit.purescript.org/packages/purescript-infinite-lists/1.0.0/docs/Data.List.Infinite) before I saw this issue.

Although, I added Eq and Ord because I found them useful.

**Comment by rightfold** [comment]
How are `eq` and `compare` useful if they never return?

**Comment by rightfold** [comment]
@Thimoteus how useful is `Eq` really, when `eq` only ever returns `False`?

**Comment by Thimoteus** [comment]
Good question @rightfold . The case I had in mind was for countably infinite unions of countably infinite sets, sort of like what you do when showing that the rationals have the cardinality of the naturals.

Consider the following:

```purescript
nats :: List Int
nats = iterate (add 1) 0

nats2 :: List (List Int)
nats2 = repeat nats

zeroes :: List Int
zeroes = repeat 0

nats3 :: List (List Int)
nats3 = insert zeroes nats2

isItZero :: Int
isItZero = head $ head $ nats3
```

since `insert :: forall a. Ord a => a -> List a -> List a` is being used such that `a ~ List Int`, which means we need an Ord instance for List a, which means we need an Eq instance since Ord extends Eq.

Also, isItZero is not equal to bottom -- I checked ;)

**Comment by matthewleon** [comment]
In Haskell-land these seem to generally be referred to as "streams", no?

https://hackage.haskell.org/package/Stream-0.4.7.2
https://hackage.haskell.org/package/streams

I've been working on something similar for PS. Just needing to debug some issues with GC before I post anything here.

**Comment by rightfold** [comment]
Read a Conal post about streams just today! 😄 Yeah seems like it.

**Comment by hdgarrood** [comment]
While a library for infinite streams does seem useful, I don't think it needs to be part of this library necessarily, and there doesn't seem to be that much demand for it (judging by the activity on this issue).
